[project]
name = "fastdca-p1"
version = "0.1.0"
description = "Dependency Injection Task 5 done by NIRMA QURESHI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
]
